name: Build on Ubuntu

on: workflow_call

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    name: Build on Ubuntu
    env:
      DISPLAY: ":99.0"
      CI: true
    steps:
      - uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        name: Start Xvfb
      - run: bun install --frozen-lockfile
      - run: bun run vscode:prepublish
      - run: bun run test-compile
      - run: bun run test
        name: Test
      - run: bun run lint
        name: Lint
