name: Build on MacOS

on: workflow_call

jobs:
  macos-build:
    runs-on: macos-latest
    name: Build on MacOS
    env:
      CI: true
    steps:
      - uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run vscode:prepublish
      - run: bun run test-compile
      - run: bun run test
        name: Test
      - run: bun run lint
        name: Lint
